version: '3.8'

services:
  lettech-marketing-site-db:
    image: postgres:16
    container_name: lettech-marketing-site-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"