spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: lettech
    password: lettech
    url: jdbc:postgresql://localhost/lettech_marketing_site
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: postgresql
  sql:
    init:
      continue-on-error: on